stages:
  fetch_market_data:
    cmd: python scripts/data/fetch_market_data.py --config configs/data/fetch.yaml
    deps:
      - scripts/data/fetch_market_data.py
      - configs/data/fetch.yaml
    outs:
      - data/raw/market:
          cache: true
  
  build_features:
    cmd: python scripts/data/build_features.py --config configs/data/features.yaml
    deps:
      - scripts/data/build_features.py
      - configs/data/features.yaml
      - data/raw/market
    outs:
      - data/processed/features:
          cache: true
  
  snapshot_config:
    cmd: >
      python scripts/validation/snapshot_config.py
      --agents-config configs/agents.yaml
      --training-config configs/training/strategy.yaml
      --feature-catalog FEATURE_CATALOG.md
      --output artifacts/config_snapshot.json
      --dvc-metrics artifacts/config_metrics.json
    deps:
      - scripts/validation/snapshot_config.py
      - configs/agents.yaml
      - configs/training/strategy.yaml
      - FEATURE_CATALOG.md
    outs:
      - artifacts/config_snapshot.json:
          cache: false
    metrics:
      - artifacts/config_metrics.json:
          cache: false
  
  reconcile_data:
    cmd: >
      python scripts/validation/reconcile_data.py
      --historical data/historical/dukascopy
      --live data/raw/market
      --output reports/reconciliation_report.json
      --validation-log reports/validation.log
    deps:
      - scripts/validation/reconcile_data.py
      - data/historical/dukascopy
      - data/raw/market
    outs:
      - reports/reconciliation_report.json:
          cache: false
      - reports/validation.log:
          cache: false
  
  train_model:
    cmd: python scripts/training/train_strategy.py --config configs/training/strategy.yaml
    deps:
      - scripts/training/train_strategy.py
      - configs/training/strategy.yaml
      - data/processed/features
    outs:
      - artifacts/models/latest:
          cache: true
    metrics:
      - artifacts/metrics/latest.json:
          cache: false
