global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'autotrader-dev'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

# Rule files for alerts
# rule_files:
#   - /etc/prometheus/rules/*.yml

scrape_configs:
  # Application metrics server
  - job_name: metrics
    static_configs:
      - targets:
          - metrics:9091
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'python_gc_.*'
        action: drop  # Drop verbose GC metrics

  # FastAPI application
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000
    scrape_interval: 10s  # Higher frequency for API metrics

  # MLflow tracking server (if it exposes metrics)
  - job_name: mlflow
    static_configs:
      - targets:
          - mlflow:5000
    scrape_interval: 30s

  # Prefect server
  - job_name: prefect
    static_configs:
      - targets:
          - prefect:4200
    scrape_interval: 30s

  # Worker Services
  - job_name: workers
    static_configs:
      - targets:
          - worker-ingestion:9100
          - worker-backtest:9101
          - worker-optimization:9102
        labels:
          service: 'worker'
    scrape_interval: 15s  # Match global default
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'worker_.*'
        action: keep  # Only keep worker-specific metrics

  # Compliance exporter
  - job_name: compliance_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - compliance-exporter:9090
    scrape_interval: 15s

  # PostgreSQL exporter (requires postgres_exporter sidecar)
  # - job_name: postgres
  #   static_configs:
  #     - targets:
  #         - postgres-exporter:9187

  # Redis exporter (requires redis_exporter sidecar)
  # - job_name: redis
  #   static_configs:
  #     - targets:
  #         - redis-exporter:9121

  # Kafka exporter (requires kafka_exporter sidecar)
  # - job_name: kafka
  #   static_configs:
  #     - targets:
  #         - kafka-exporter:9308
