global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: metrics
    static_configs:
      - targets:
          - metrics:9091

  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000
