# BounceHunter Configuration - Canadian Margin Account
# Aggressive settings for experienced traders with margin
# Higher position sizes, more positions, lower thresholds

# ============================================================================
# AGENT SYSTEM CONFIGURATION
# ============================================================================

# Live trading toggle
live_trading: false  # Set to true after paper trading validation

# Risk controls
risk_controls:
  # Position sizing (aggressive for margin)
  size_pct_base: 0.012          # 1.2% base size (standard aggressive)
  size_pct_high_vix: 0.006      # 0.6% in high VIX (50% reduction)
  max_position_size_pct: 1.5    # 1.5% max per position
  max_positions: 8              # Max 8 concurrent positions
  
  # Drawdown limits
  daily_loss_limit_pct: 0.02    # 2% daily max loss
  max_drawdown_pct: 0.10        # 10% max drawdown before pause
  
  # Performance thresholds
  min_hit_rate: 0.40            # Eject tickers below 40% hit rate
  min_sample_size: 10           # Need 10+ trades to calculate hit rate

# Entry thresholds
scanner:
  min_bcs: 0.62                 # Lower threshold (aggressive, 62nd percentile)
  min_volume: 1_000_000         # 1M+ volume
  
  blackouts:
    earnings_days: 2            # Skip 2 days before earnings
    
  price_filters:
    min_price: 5.0              # $5+ stocks (wider range)
    max_price: 1000.0           # Under $1000
    
  excluded_sectors:
    - "Utilities"               # Low volatility (skip)

# Exit rules
exits:
  profit_target_pct: 0.03       # 3% profit target
  stop_loss_pct: 0.02           # 2% stop loss (1.5:1 R/R)
  trailing_stop_pct: 0.015      # 1.5% trailing stop
  max_holding_days: 10          # Exit after 10 days max

# Regime detection
regime:
  vix_high_threshold: 20.0      # VIX > 20 = high volatility
  spy_dma_period: 200           # SPY 200-day moving average
  
  # Adjustments per regime
  adjustments:
    high_vix:
      size_multiplier: 0.5      # 50% size in high VIX
      min_bcs_adj: 0.05         # Raise BCS by 5% (0.62 → 0.67)
    low_spy:
      size_multiplier: 0.7      # 70% size when SPY weak
      max_positions_adj: -2     # Reduce max positions by 2

# ============================================================================
# TELEGRAM NOTIFICATIONS (Recommended)
# ============================================================================
telegram_bot:
  enabled: false                # Set to true after setup
  bot_token: "YOUR_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"
  
  # Notification settings
  notify_on:
    - "entry_signal"            # New buy signals
    - "exit"                    # Position exits
    - "veto"                    # Vetoed signals
    - "daily_summary"           # End-of-day summary
    - "drawdown_alert"          # Critical drawdown alerts

# ============================================================================
# AGENT WEIGHTS (Balanced Learning)
# ============================================================================
agents:
  sentiment:
    enabled: true
    veto_weight: 0.20           # Standard weight for sentiment
    
  forecast:
    enabled: true
    confidence_threshold: 0.40  # Standard threshold
    
  risk:
    enabled: true
    strict_mode: false          # Normal risk checks (not overly strict)
    
  news:
    enabled: true
    check_window_hours: 24      # Check last 24 hours of news

# ============================================================================
# MEMORY & LEARNING
# ============================================================================
memory:
  database: "margin_memory.db"  # Separate DB for margin tracking
  
  learning:
    enabled: true
    update_frequency: "daily"   # Update hit rates daily
    
  audit:
    frequency: "weekly"         # Run audit weekly
    min_confidence_floor: 0.30  # Don't drop below 30% confidence

# ============================================================================
# NOTES FOR CANADIAN MARGIN TRADERS
# ============================================================================
# 
# Margin Requirements (typical):
# - Questrade: 30% maintenance margin for stocks
# - IBKR: 25% maintenance margin (varies by stock)
# 
# Position Sizing Example (on $100k account, 2:1 margin):
# - Buying power: $200k (with margin)
# - Base size: 1.2% of $100k = $1,200 per position
# - Max 8 positions = $9,600 max exposure (9.6% of equity)
# - Note: Sizing is % of EQUITY, not buying power (safer)
# 
# Expected Performance:
# - Hit rate: 55-60%
# - Avg gain: 3%
# - Avg loss: 2%
# - Expectancy: 1.5% per trade
# - Annual trades: ~120 (aggressive scanning)
# - Expected annual return: ~15-20% (compounded)
# 
# Margin Risks:
# - Margin calls if equity < 30% of position value
# - Interest charges on borrowed funds (~6-8% annually)
# - Higher losses if wrong (leverage cuts both ways)
# 
# Risk Management:
# - 1.2% sizing limits downside per trade
# - 8 position max prevents over-leverage
# - Stop losses enforced (2% max loss per trade)
# - Daily loss limit (2%) prevents margin calls
# - Drawdown circuit breaker at 10%
# 
# Recommended Broker:
# - IBKR: Best for margin ($1 commissions, 1.83% margin rate)
# - Questrade: Higher margin rates (~6%), but Canadian company
# 
# Margin Interest (approximate):
# - IBKR: 1.83% - 6.83% depending on balance
# - Questrade: 6.0% - 9.25% depending on balance
# 
# Example Cost (on $10k margin for 1 month):
# - IBKR: $10,000 * 0.0683 / 12 = $57/month
# - Questrade: $10,000 * 0.09 / 12 = $75/month
# 
# Tax Considerations (non-registered account):
# - 50% of gains taxed as capital gains
# - Margin interest is tax-deductible (investment expense)
# - Keep detailed records for CRA reporting
# 
# Usage:
# python -m bouncehunter.agentic_cli \
#   --mode scan \
#   --broker ibkr \
#   --broker-port 7497 \
#   --config configs/canadian_margin.yaml
# 
# ============================================================================
