# Grafana Cloud Configuration (example)
# Copy to grafana_cloud.yaml and fill placeholders, but do NOT commit secrets.

# Token Details
token_name: autotrader
expiration: No expiry
scopes: alloy-data-write

# API Token: set at runtime via environment variables or secret manager
# Example: $env:GRAFANA_CLOUD_METRICS_TOKEN = "glc_..."
grafana_cloud_token: "<SET_VIA_ENV_OR_SECRET>"

# Stack Info
organization_id: "<YOUR_ORG_ID>"
stack_id: "<YOUR_METRICS_INSTANCE_ID>"
region: "prod-ca-east-0"

# Endpoints (provided by Grafana Cloud)
# metrics_endpoint: https://prometheus-<region>.grafana.net/api/prom/push
# logs_endpoint: https://logs-<region>.grafana.net/loki/api/v1/push
# traces_endpoint: https://tempo-<region>.grafana.net/tempo

# Usage Notes:
# 1. Do not store tokens in files. Use env vars or secret managers.
# 2. Alloy config should read basic_auth from env():
#      username = env("GRAFANA_CLOUD_METRICS_USERNAME")
#      password = env("GRAFANA_CLOUD_METRICS_TOKEN")
# 3. Run Alloy using the provided PowerShell script: scripts/run_alloy.ps1
