# PennyHunter: Microcap preset for BounceHunter
# Built for $200 account, 1 position max, $5 risk per trade
# Focus: liquid microcaps $0.20-$5.00, VWAP-based runner + mean-revert plays

name: PennyHunter
description: "Disciplined microcap trading ($200 starter account)"

# ===== UNIVERSE FILTERS (Strict liquidity + quality) =====
universe:
  # Ticker list (validated by build_ticker_universe.py)
  ticker_file: configs/under10_tickers.txt
  
  exchanges: 
    - NASDAQ
    - NYSE
    - AMEX
    # - TSX        # Uncomment for Canadian small caps
    # - TSXV       # Uncomment for venture exchange
  
  # Price band (avoid sub-$0.20 noise, extended for current market)
  price_min: 0.20
  price_max: 10.00               # RELAXED from $5 to $10 (captures SPCE, EVGO, OPEN, etc.)
  
  # Liquidity requirements (RELAXED for current penny market - Oct 2025)
  min_avg_dollar_vol: 500000     # $500k avg daily dollar volume (10d rolling) - RELAXED from 1.5M
  min_avg_volume: 200000          # 200k shares/day minimum (10d rolling) - RELAXED from 300k
  max_spread_pct: 2.5             # Exclude if spread > 2.5% (slippage tolerance) - RELAXED from 1.5%
  
  # Float/dilution (if data available) - PHASE 1: Tightened for higher win rate
  float_max_millions: 20          # PHASE 1: Lowered from 50M to 20M (tighter supply)
  float_sweet_spot_min: 5         # PHASE 1: Prefer 5-20M float (explosive potential)
  exclude_otc: true               # No OTC (liquidity risk, manipulation)
  
  # Corporate health
  exclude_going_concern: true     # Skip 8-K going concern warnings
  exclude_reg_halted: true        # Skip tickers with regulatory halts

# ===== SIGNAL MODULES (Long-only, 2 playbooks) =====
signals:
  
  # Playbook A: High-Volume Runner (momentum)
  runner_vwap:
    enabled: true
    
    # Setup requirements
    premarket_gap_min_pct: 20           # Must gap ≥ +20% in premarket
    open_above_pm_vwap: true            # Open above PM VWAP
    vwap_reclaim_window_min: 180        # Look for reclaim in first 3 hours
    
    # PHASE 1: Confluence filters (require multiple signals)
    min_confluence_signals: 2           # PHASE 1: Require 2 of 3 (vwap_reclaim + volume_spike + rsi_recovery)
    confirmation_bars: 2                # PHASE 1: Wait 2 bars after VWAP reclaim (reduces false breakouts)
    require_premarket_strength: true    # PHASE 1: PM volume must be >1.5× daily avg
    premarket_volume_mult: 1.5          # PHASE 1: PM volume threshold
    
    # Entry trigger
    volume_spike_mult: 2.5              # 1-min volume ≥ 2.5× 20-bar avg
    max_spread_pct: 1.5                 # Abort if spread widens > 1.5%
    entry_type: vwap_reclaim            # Enter on VWAP reclaim OR PM high break
    rsi_recovery_threshold: 30          # PHASE 1: RSI must cross above 30 for confluence
    
    # Exit rules
    take_profit_pct: [8, 15]            # Scale: 50% at +8%, rest at +15%
    stop_loss_type: vwap_fail           # Stop if breaks below VWAP
    time_stop_min: 40                   # Exit if no move in 40 minutes
    breakeven_stop_trigger_pct: 3       # PHASE 1: Move stop to breakeven at +3%
    
    # Risk/sizing
    max_risk_pct: 2.5                   # Max 2.5% account risk per trade
    position_size_dollars: 50           # ~$50 position (allow $5 risk at 10% stop)
    
    # PHASE 1: Signal scoring
    min_signal_score: 7.0               # PHASE 1: Minimum score to trade (0-10)

  # Playbook B: First Red Day Bounce (mean-reversion)
  frd_bounce:
    enabled: true
    
    # Setup requirements
    prior_day_range_mult_atr: 2.5       # Prior day range > 2.5× ATR(14)
    prior_day_close_in_top_pct: 50      # PHASE 1: Raised from 30% to 50% (stronger prior day)
    nextday_gap_direction: down         # Must gap down next day
    
    # PHASE 1: Confluence filters
    require_volume_climax: true         # PHASE 1: Flush must have volume spike (capitulation)
    volume_climax_mult: 2.5             # PHASE 1: Volume ≥2.5× avg on flush bar
    confirmation_bars: 2                # PHASE 1: Wait 2 bars after reclaim
    check_support_confluence: true      # PHASE 1: Flush should hit prior support level
    
    # Entry trigger
    rsi2_max: 5                         # RSI(2) < 5 (panic flush)
    z_vwap_band_entry: -2.0             # Entry at -2σ below VWAP bands
    entry_confirmation: reclaim         # Wait for reclaim of flush candle high
    entry_time_window: [10, 11]         # PHASE 1: Prefer 10-11 AM bounces (after morning panic)
    
    # Exit rules
    take_profit_pct: [5, 10]            # Scale: 50% at +5%, rest at +10%
    stop_loss_pct: 4                    # Hard stop at -4% (tight for mean-revert)
    time_stop_min: 180                  # Exit if no move in 3 hours
    breakeven_stop_trigger_pct: 3       # PHASE 1: Move stop to breakeven at +3%
    
    # Risk/sizing
    max_risk_pct: 2.5                   # Max 2.5% account risk
    position_size_dollars: 50           # ~$50 position
    
    # PHASE 1: Signal scoring
    min_signal_score: 7.0               # PHASE 1: Minimum score to trade (0-10)

# ===== GUARDS (Penny-specific risk controls) =====
guards:
  # PHASE 1: Market regime filters (CRITICAL for win rate)
  market_regime:
    enabled: true                       # PHASE 1: Enable market regime checking
    require_spy_above_200ma: true       # PHASE 1: Only trade when SPY > 200MA
    require_spy_green_day: false        # PHASE 1: Don't require green day (too strict)
    max_vix_level: 30                   # PHASE 1: Skip when VIX > 30 (risk-off)
    vix_low_threshold: 20               # VIX < 20 = optimal
    vix_medium_threshold: 25            # VIX 20-25 = acceptable
    cache_minutes: 15                   # Cache regime data for 15min
  
  # Corporate events
  earnings_window_days: 1               # Skip within 1 day of earnings
  skip_offering_news: true              # Skip ATM/direct offerings (24-48h)
  skip_convertible_filings: true        # Skip after convertible note filings
  
  # Market mechanics
  skip_if_ssr_on_for_shorts: true       # SSR awareness (not shorting, but affects behavior)
  halt_blacklist_minutes: 15            # Skip for 15min after halt resumption
  max_halt_count_today: 2               # Skip if halted 2+ times today
  
  # Liquidity
  min_bid_ask_size: 5000                # Require ≥ 5k shares on bid/ask
  max_spread_breach_pct: 2.0            # Abort if spread breaches 2% intraday
  
  # Float/dilution
  check_recent_dilution: true           # Flag if shares outstanding increased
  max_days_since_offering: 2            # Skip 2 days after offering closes

# ===== RISK MANAGEMENT (Tailored for $200 account) =====
risk:
  # Position limits
  max_concurrent_positions: 1           # ONE trade at a time
  max_positions_per_day: 3              # Max 3 attempts/day (prevent overtrading)
  
  # Sizing
  per_trade_risk_dollars: 5             # Risk $5 per trade (2.5% of $200)
  position_size_method: fixed_dollar    # Use fixed ~$50 positions
  
  # Execution
  order_type: limit                     # Always use limit orders
  limit_offset_pct: 0.1                 # Place limit 0.1% from midpoint
  slippage_bps_assumption: 40           # Assume 0.40% slippage for backtests
  
  # Circuit breakers
  daily_loss_limit_dollars: 15          # Stop if down $15 in a day (3 losses)
  max_drawdown_pct: 10                  # Stop if account down 10% from high
  
  # Time-based
  trading_hours_only: true              # No after-hours execution
  no_trade_first_15min: true            # Avoid open volatility
  no_trade_last_30min: true             # Avoid close volatility

# ===== ALERTS (Telegram notifications) =====
alerts:
  channel: telegram
  
  # Trigger conditions
  on_signal: true                       # Alert when signal fires
  on_entry: true                        # Alert when position opened
  on_exit: true                         # Alert when position closed
  on_stop: true                         # Alert when stopped out
  
  # Alert content (penny-specific)
  include_float: true                   # Show float if available
  include_spread: true                  # Show current spread
  include_ssr_status: true              # Show if SSR active
  include_halt_history: true            # Show halt count today
  include_vwap_levels: true             # Show VWAP + bands
  include_volume_profile: true          # Show volume spike magnitude

# ===== DATA SOURCES =====
data:
  # Intraday (requires Questrade or similar)
  intraday_provider: questrade          # Use Questrade IQ feed when available
  intraday_interval: 1min               # 1-minute bars for entries
  
  # EOD fallback (while setting up intraday)
  eod_provider: yfinance                # Fallback for nightly screening
  
  # Lookback periods
  history_days: 30                      # 30 days for ATR, volume averages
  premarket_start: "04:00"              # Start tracking PM at 4 AM ET
  market_open: "09:30"                  # Market open 9:30 AM ET
  market_close: "16:00"                 # Market close 4:00 PM ET

# ===== BACKTESTING (EOD approximation) =====
backtest:
  initial_capital: 200                  # Start with $200
  commission_per_trade: 5.00            # Questrade: $4.95-$9.95/trade
  slippage_model: penny_realistic       # Use penny-aware slippage
  
  # Metrics
  track_win_rate: true
  track_profit_factor: true
  track_sharpe: true
  track_max_drawdown: true
  
  # Reporting
  min_trades_for_stats: 20              # Need 20 trades for meaningful stats
  report_by_signal: true                # Break down by runner vs FRD
  report_by_ticker: true                # Identify which tickers work

# ===== FEATURE FLAGS =====
features:
  use_agentic_v2: true                  # Enable V2 reasoning (when ready)
  use_vwap_engine: true                 # Enable VWAP calculations
  use_halt_detector: true               # Monitor for halts
  use_ssr_tracker: true                 # Track SSR status
  use_news_guard: true                  # Filter offering/dilution news
  
  # Advanced (disable until proven)
  use_level2_data: false                # Level 2 DOM (future enhancement)
  use_short_interest: false             # Short interest (future)
  use_float_rotation: false             # Float rotation metrics (future)

# ===== ADVANCED RISK FILTERS (NEW - Oct 2025) =====
advanced_filters:
  enabled: true                         # Enable advanced quality gates
  
  liquidity_health:
    enabled: true
    delta_threshold_pct: -30.0          # Max allowed volume decline (14d vs 7d)
    
  slippage_control:
    enabled: true
    max_slippage_pct: 5.0               # Max acceptable slippage estimate
    
  financial_health:
    enabled: true
    min_cash_runway_months: 6.0         # Minimum cash runway (if data available)
    
  diversification:
    enabled: true
    max_per_sector: 3                   # Max positions per sector
    
  breakout_quality:
    enabled: true
    check_volume_fade: true             # Reject if volume fading

# ===== LOGGING/MONITORING =====
logging:
  level: INFO
  log_all_signals: true                 # Log even rejected signals
  log_guard_rejections: true            # Why signals were rejected
  log_execution_details: true           # Entry/exit timing, fills
  
monitoring:
  track_spread_changes: true            # Alert if spread widens
  track_halt_events: true               # Log halt/resume
  track_volume_spikes: true             # Log unusual volume
  track_news_events: true               # Log earnings, offerings, etc.

# ===== PHASE 2.5: MEMORY SYSTEM (Auto-Eject Underperformers) =====
memory:
  enabled: true                         # Enable memory-based auto-ejection
  db_path: reports/pennyhunter_memory.db  # SQLite database path
  min_trades_for_ejection: 4            # Minimum trades before considering ejection
  ejection_win_rate_threshold: 0.35     # Auto-eject if <35% win rate (was 0.40)
  monitor_win_rate_threshold: 0.45      # Monitor/flag if <45% win rate (was 0.50)
  # Ejected tickers are blocked from future trades
  # Monitored tickers are allowed but flagged for review

# ===== PHASE 3: AGENTIC INTELLIGENCE SYSTEM =====
agentic:
  enabled: false                        # Enable 8-agent agentic system (set true to activate)
  
  # Confidence Thresholds (gem_score based)
  min_confidence: 7.0                   # Base confidence threshold (vs 5.5 non-agentic)
  min_confidence_highvix: 7.5           # Higher bar in high VIX regime
  min_confidence_stress: 8.0            # Even higher bar in SPY stress
  
  # Portfolio Management
  max_concurrent: 5                     # Maximum concurrent positions
  max_per_sector: 2                     # Maximum positions per sector
  allow_earnings: false                 # Block trades in earnings windows
  preclose_only: false                  # Only trade in pre-close period (3PM+)
  
  # Position Sizing (% of portfolio per position)
  risk_pct_normal: 0.01                 # 1% per position in normal regime
  risk_pct_highvix: 0.005               # 0.5% per position in high VIX
  risk_pct_stress: 0.0025               # 0.25% per position in SPY stress
  
  # News Sentiment
  news_veto_enabled: false              # Enable NewsSentry agent (requires news API)
  
  # Adaptive Learning
  auto_adapt_thresholds: true           # Automatically adjust thresholds based on performance
  base_rate_floor: 0.40                 # Eject tickers below 40% win rate
  min_sample_size: 10                   # Minimum trades before adaptive ejection
  adapt_after_n_trades: 20              # Start adapting after this many total trades
  
  # Memory Integration
  use_existing_memory: true             # Integrate with Phase 2.5 memory system
  memory_db_path: reports/pennyhunter_memory.db      # Base memory database
  agentic_db_path: reports/pennyhunter_agentic.db    # Agentic-specific database
  
  # Live Trading (if broker integration enabled)
  live_trading: false                   # Execute actual trades (vs paper/alerts)

