name: Integration Tests

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

# Cancel in-progress runs for same branch/PR (but not scheduled runs)
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name != 'schedule' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name != 'schedule' }}

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        env:
          TEST_MODE: integration
        run: |
          if [ -d "tests/integration" ]; then
            pytest tests/integration/ \
              --maxfail=1 \
              --tb=short \
              -v
          else
            echo "No integration tests directory found, skipping..."
          fi

      - name: Run broker integration tests (mocked)
        run: |
          pytest tests/test_broker.py \
            tests/test_bouncehunter_engine.py \
            tests/test_agentic.py \
            -v || echo "Some integration tests not found, continuing..."

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: integration-test-results
          path: |
            test-results/
            *.log
          retention-days: 7
